import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  AirVent,
  AlarmClock,
  Ambulance,
  Anchor,
  Apple,
  Archive,
  Armchair,
  Baby,
  BadgePercent,
  Balloon,
  Banknote,
  Bath,
  BedDouble,
  Beer,
  Bell,
  Bike,
  Bird,
  Bluetooth,
  Book,
  BookOpen,
  Bone,
  Box,
  Brain,
  Briefcase,
  Brush,
  Building2,
  Bus,
  Cable,
  CakeSlice,
  Calculator,
  Calendar,
  Camera,
  Car,
  CarFront,
  Castle,
  Cat,
  ChartColumn,
  Cherry,
  Church,
  CircuitBoard,
  Clapperboard,
  Clock,
  Coffee,
  Compass,
  CookingPot,
  Cpu,
  CreditCard,
  Croissant,
  Cross,
  Crown,
  CupSoda,
  Dog,
  DoorOpen,
  Drama,
  Droplets,
  Dumbbell,
  Earth,
  Factory,
  Fan,
  FerrisWheel,
  FileText,
  Film,
  Fish,
  Flame,
  FlaskConical,
  Flower2,
  Footprints,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  Gift,
  Glasses,
  Globe,
  Goal,
  GraduationCap,
  Hammer,
  Handshake,
  HardDrive,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Hospital,
  Hotel,
  IceCreamCone,
  Image,
  KeyRound,
  Keyboard,
  Lamp,
  Landmark,
  Languages,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  Lock,
  Luggage,
  Mail,
  Map,
  MapPin,
  Martini,
  Medal,
  Megaphone,
  MessageCircle,
  Mic,
  Microscope,
  Milk,
  Monitor,
  Moon,
  Mountain,
  Mouse,
  Music,
  Navigation,
  Newspaper,
  NotebookPen,
  Package,
  Paintbrush,
  Palmtree,
  ParkingCircle,
  PartyPopper,
  PawPrint,
  PenTool,
  Pencil,
  PersonStanding,
  Phone,
  Pill,
  Pizza,
  Plane,
  Printer,
  Puzzle,
  Rabbit,
  Radio,
  Receipt,
  Recycle,
  Refrigerator,
  Router,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  Scale,
  School,
  Scissors,
  Settings,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  ShowerHead,
  Smartphone,
  Sofa,
  Soup,
  Sparkles,
  Speaker,
  SprayCan,
  Star,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Tablet,
  Tag,
  Tent,
  Ticket,
  ToyBrick,
  TrafficCone,
  TrainFront,
  Trash2,
  Trees,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Usb,
  UserRound,
  Users,
  Utensils,
  UtensilsCrossed,
  Video,
  Volleyball,
  Wallet,
  Warehouse,
  Watch,
  Waves,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from 'lucide-react'

export const ACTIVITY_ICON_OPTIONS: { key: string; label: string; Icon: LucideIcon }[] = [
  { key: 'Smartphone', label: 'Telefon', Icon: Smartphone },
  { key: 'Tablet', label: 'Planshet', Icon: Tablet },
  { key: 'Laptop', label: 'Noutbuk', Icon: Laptop },
  { key: 'Monitor', label: 'Monitor', Icon: Monitor },
  { key: 'Tv', label: 'TV', Icon: Tv },
  { key: 'Cpu', label: 'Protsessor', Icon: Cpu },
  { key: 'HardDrive', label: 'Disk', Icon: HardDrive },
  { key: 'Wifi', label: 'Wifi', Icon: Wifi },
  { key: 'Bluetooth', label: 'Bluetooth', Icon: Bluetooth },
  { key: 'Camera', label: 'Kamera', Icon: Camera },
  { key: 'Headphones', label: 'Quloqchin', Icon: Headphones },
  { key: 'Speaker', label: 'Karnay', Icon: Speaker },
  { key: 'Radio', label: 'Radio', Icon: Radio },
  { key: 'Printer', label: 'Printer', Icon: Printer },
  { key: 'Keyboard', label: 'Klaviatura', Icon: Keyboard },
  { key: 'Mouse', label: 'Sichqoncha', Icon: Mouse },
  { key: 'Gamepad2', label: 'O‘yin', Icon: Gamepad2 },
  { key: 'Watch', label: 'Soat', Icon: Watch },
  { key: 'Cable', label: 'Kabel', Icon: Cable },
  { key: 'CircuitBoard', label: 'Plata', Icon: CircuitBoard },
  { key: 'Usb', label: 'USB', Icon: Usb },
  { key: 'Router', label: 'Router', Icon: Router },
  { key: 'Satellite', label: 'Sun’iy yo‘ldosh', Icon: Satellite },
  { key: 'Shirt', label: 'Kiyim', Icon: Shirt },
  { key: 'ShoppingBag', label: 'Sumka', Icon: ShoppingBag },
  { key: 'ShoppingBasket', label: 'Savat', Icon: ShoppingBasket },
  { key: 'ShoppingCart', label: 'Aravacha', Icon: ShoppingCart },
  { key: 'Gem', label: 'Tosh', Icon: Gem },
  { key: 'Glasses', label: 'Ko‘zoynak', Icon: Glasses },
  { key: 'Footprints', label: 'Oyoq kiyim', Icon: Footprints },
  { key: 'Crown', label: 'Toj', Icon: Crown },
  { key: 'Sparkles', label: 'Porloq', Icon: Sparkles },
  { key: 'Scissors', label: 'Qaychi', Icon: Scissors },
  { key: 'SprayCan', label: 'Sprey', Icon: SprayCan },
  { key: 'Wrench', label: 'Kalit', Icon: Wrench },
  { key: 'Hammer', label: 'Bolg‘a', Icon: Hammer },
  { key: 'Paintbrush', label: 'Cho‘tka', Icon: Paintbrush },
  { key: 'Brush', label: 'Brush', Icon: Brush },
  { key: 'Ruler', label: 'Chizg‘ich', Icon: Ruler },
  { key: 'Home', label: 'Uy', Icon: Home },
  { key: 'Sofa', label: 'Divan', Icon: Sofa },
  { key: 'Armchair', label: 'Kreslo', Icon: Armchair },
  { key: 'BedDouble', label: 'Yotoq', Icon: BedDouble },
  { key: 'Lamp', label: 'Lampa', Icon: Lamp },
  { key: 'Lightbulb', label: 'Lampochka', Icon: Lightbulb },
  { key: 'DoorOpen', label: 'Eshik', Icon: DoorOpen },
  { key: 'KeyRound', label: 'Kalitcha', Icon: KeyRound },
  { key: 'Lock', label: 'Qulf', Icon: Lock },
  { key: 'Fan', label: 'Ventilyator', Icon: Fan },
  { key: 'AirVent', label: 'Konditsioner', Icon: AirVent },
  { key: 'Bath', label: 'Vanna', Icon: Bath },
  { key: 'ShowerHead', label: 'Dush', Icon: ShowerHead },
  { key: 'Refrigerator', label: 'Muzlatgich', Icon: Refrigerator },
  { key: 'Package', label: 'Quti', Icon: Package },
  { key: 'Box', label: 'Karobka', Icon: Box },
  { key: 'Archive', label: 'Arxiv', Icon: Archive },
  { key: 'Warehouse', label: 'Ombor', Icon: Warehouse },
  { key: 'Heart', label: 'Yurak', Icon: Heart },
  { key: 'HeartPulse', label: 'Puls', Icon: HeartPulse },
  { key: 'Stethoscope', label: 'Stetoskop', Icon: Stethoscope },
  { key: 'Pill', label: 'Dori', Icon: Pill },
  { key: 'Cross', label: 'Tibbiyot', Icon: Cross },
  { key: 'Syringe', label: 'Shprits', Icon: Syringe },
  { key: 'Ambulance', label: 'Tez yordam', Icon: Ambulance },
  { key: 'Hospital', label: 'Kasalxona', Icon: Hospital },
  { key: 'Activity', label: 'Faollik', Icon: Activity },
  { key: 'Brain', label: 'Miya', Icon: Brain },
  { key: 'Bone', label: 'Suyak', Icon: Bone },
  { key: 'Baby', label: 'Bola', Icon: Baby },
  { key: 'ToyBrick', label: 'O‘yinchoq', Icon: ToyBrick },
  { key: 'Puzzle', label: 'Puzzle', Icon: Puzzle },
  { key: 'Balloon', label: 'Sharik', Icon: Balloon },
  { key: 'FerrisWheel', label: 'Attraksion', Icon: FerrisWheel },
  { key: 'Palmtree', label: 'Palma', Icon: Palmtree },
  { key: 'Umbrella', label: 'Soyabon', Icon: Umbrella },
  { key: 'Tent', label: 'Chodir', Icon: Tent },
  { key: 'Mountain', label: 'Tog‘', Icon: Mountain },
  { key: 'Trees', label: 'Daraxt', Icon: Trees },
  { key: 'Flower2', label: 'Gul', Icon: Flower2 },
  { key: 'Sun', label: 'Quyosh', Icon: Sun },
  { key: 'Moon', label: 'Oy', Icon: Moon },
  { key: 'Music', label: 'Musiqa', Icon: Music },
  { key: 'Film', label: 'Kino', Icon: Film },
  { key: 'Clapperboard', label: 'Klaker', Icon: Clapperboard },
  { key: 'Drama', label: 'Teatr', Icon: Drama },
  { key: 'Ticket', label: 'Chipta', Icon: Ticket },
  { key: 'PartyPopper', label: 'Bayram', Icon: PartyPopper },
  { key: 'Wine', label: 'Vino', Icon: Wine },
  { key: 'Coffee', label: 'Qahva', Icon: Coffee },
  { key: 'Beer', label: 'Pivo', Icon: Beer },
  { key: 'Martini', label: 'Kokteyl', Icon: Martini },
  { key: 'CupSoda', label: 'Ichimlik', Icon: CupSoda },
  { key: 'Utensils', label: 'Idish', Icon: Utensils },
  { key: 'UtensilsCrossed', label: 'Restoran', Icon: UtensilsCrossed },
  { key: 'CookingPot', label: 'Qozon', Icon: CookingPot },
  { key: 'Pizza', label: 'Pitsa', Icon: Pizza },
  { key: 'IceCreamCone', label: 'Muzqaymoq', Icon: IceCreamCone },
  { key: 'Apple', label: 'Olma', Icon: Apple },
  { key: 'Cherry', label: 'Gilos', Icon: Cherry },
  { key: 'Salad', label: 'Salat', Icon: Salad },
  { key: 'Soup', label: 'Sho‘rva', Icon: Soup },
  { key: 'CakeSlice', label: 'Tort', Icon: CakeSlice },
  { key: 'Croissant', label: 'Non', Icon: Croissant },
  { key: 'Sandwich', label: 'Sendvich', Icon: Sandwich },
  { key: 'Milk', label: 'Sut', Icon: Milk },
  { key: 'GraduationCap', label: 'Diplom', Icon: GraduationCap },
  { key: 'School', label: 'Maktab', Icon: School },
  { key: 'Book', label: 'Kitob', Icon: Book },
  { key: 'BookOpen', label: 'Ochiq kitob', Icon: BookOpen },
  { key: 'Library', label: 'Kutubxona', Icon: Library },
  { key: 'Pencil', label: 'Qalam', Icon: Pencil },
  { key: 'PenTool', label: 'Dizayn', Icon: PenTool },
  { key: 'NotebookPen', label: 'Daftar', Icon: NotebookPen },
  { key: 'Languages', label: 'Tillar', Icon: Languages },
  { key: 'Microscope', label: 'Mikroskop', Icon: Microscope },
  { key: 'FlaskConical', label: 'Laboratoriya', Icon: FlaskConical },
  { key: 'Dumbbell', label: 'Sport', Icon: Dumbbell },
  { key: 'Bike', label: 'Velosiped', Icon: Bike },
  { key: 'Trophy', label: 'Kubok', Icon: Trophy },
  { key: 'Medal', label: 'Medal', Icon: Medal },
  { key: 'Volleyball', label: 'Voleybol', Icon: Volleyball },
  { key: 'Goal', label: 'Darvoza', Icon: Goal },
  { key: 'PersonStanding', label: 'Mashq', Icon: PersonStanding },
  { key: 'Car', label: 'Avto', Icon: Car },
  { key: 'CarFront', label: 'Mashina', Icon: CarFront },
  { key: 'Bus', label: 'Avtobus', Icon: Bus },
  { key: 'TrainFront', label: 'Poyezd', Icon: TrainFront },
  { key: 'Plane', label: 'Samolyot', Icon: Plane },
  { key: 'Ship', label: 'Kema', Icon: Ship },
  { key: 'Sailboat', label: 'Yelkan', Icon: Sailboat },
  { key: 'Truck', label: 'Yuk mashina', Icon: Truck },
  { key: 'Fuel', label: 'Yoqilg‘i', Icon: Fuel },
  { key: 'ParkingCircle', label: 'Parking', Icon: ParkingCircle },
  { key: 'TrafficCone', label: 'Yo‘l', Icon: TrafficCone },
  { key: 'Waves', label: 'Suv', Icon: Waves },
  { key: 'Anchor', label: 'Langar', Icon: Anchor },
  { key: 'Compass', label: 'Kompas', Icon: Compass },
  { key: 'Map', label: 'Xarita', Icon: Map },
  { key: 'MapPin', label: 'Manzil', Icon: MapPin },
  { key: 'Navigation', label: 'Navigatsiya', Icon: Navigation },
  { key: 'Luggage', label: 'Chamadon', Icon: Luggage },
  { key: 'Hotel', label: 'Mehmonxona', Icon: Hotel },
  { key: 'Globe', label: 'Globus', Icon: Globe },
  { key: 'Earth', label: 'Dunyo', Icon: Earth },
  { key: 'Briefcase', label: 'Portfel', Icon: Briefcase },
  { key: 'Building2', label: 'Bino', Icon: Building2 },
  { key: 'Store', label: 'Do‘kon', Icon: Store },
  { key: 'Factory', label: 'Zavod', Icon: Factory },
  { key: 'Landmark', label: 'Muassasa', Icon: Landmark },
  { key: 'Banknote', label: 'Pul', Icon: Banknote },
  { key: 'CreditCard', label: 'Karta', Icon: CreditCard },
  { key: 'Wallet', label: 'Hamyon', Icon: Wallet },
  { key: 'Receipt', label: 'Chek', Icon: Receipt },
  { key: 'Calculator', label: 'Kalkulyator', Icon: Calculator },
  { key: 'ChartColumn', label: 'Statistika', Icon: ChartColumn },
  { key: 'BadgePercent', label: 'Chegirma', Icon: BadgePercent },
  { key: 'Users', label: 'Jamoa', Icon: Users },
  { key: 'UserRound', label: 'Shaxs', Icon: UserRound },
  { key: 'Handshake', label: 'Kelishuv', Icon: Handshake },
  { key: 'Phone', label: 'Aloqa', Icon: Phone },
  { key: 'Mail', label: 'Pochta', Icon: Mail },
  { key: 'MessageCircle', label: 'Chat', Icon: MessageCircle },
  { key: 'Video', label: 'Video', Icon: Video },
  { key: 'Mic', label: 'Mikrofon', Icon: Mic },
  { key: 'Megaphone', label: 'Reklama', Icon: Megaphone },
  { key: 'PawPrint', label: 'Hayvon', Icon: PawPrint },
  { key: 'Dog', label: 'It', Icon: Dog },
  { key: 'Cat', label: 'Mushuk', Icon: Cat },
  { key: 'Bird', label: 'Qush', Icon: Bird },
  { key: 'Rabbit', label: 'Quyon', Icon: Rabbit },
  { key: 'Fish', label: 'Baliq', Icon: Fish },
  { key: 'Gift', label: 'Sovg‘a', Icon: Gift },
  { key: 'Shield', label: 'Himoya', Icon: Shield },
  { key: 'Star', label: 'Yulduz', Icon: Star },
  { key: 'Zap', label: 'Tok', Icon: Zap },
  { key: 'Flame', label: 'Olov', Icon: Flame },
  { key: 'Droplets', label: 'Suv tomchi', Icon: Droplets },
  { key: 'Leaf', label: 'Yaproq', Icon: Leaf },
  { key: 'Recycle', label: 'Qayta ishlash', Icon: Recycle },
  { key: 'Settings', label: 'Sozlama', Icon: Settings },
  { key: 'Clock', label: 'Vaqt', Icon: Clock },
  { key: 'AlarmClock', label: 'Budilnik', Icon: AlarmClock },
  { key: 'Calendar', label: 'Taqvim', Icon: Calendar },
  { key: 'Bell', label: 'Qo‘ng‘iroq', Icon: Bell },
  { key: 'Tag', label: 'Yorliq', Icon: Tag },
  { key: 'Image', label: 'Rasm', Icon: Image },
  { key: 'FileText', label: 'Hujjat', Icon: FileText },
  { key: 'Newspaper', label: 'Gazeta', Icon: Newspaper },
  { key: 'Scale', label: 'Tarozi', Icon: Scale },
  { key: 'Gavel', label: 'Sud', Icon: Gavel },
  { key: 'Church', label: 'Ibodatxona', Icon: Church },
  { key: 'Castle', label: 'Qasr', Icon: Castle },
  { key: 'Trash2', label: 'Chiqindi', Icon: Trash2 },
]

const LEGACY_ICON_KEYS: Record<string, string> = {
  Devices: 'Smartphone',
  DryCleaning: 'Shirt',
  Handyman: 'Wrench',
  Inventory2: 'Package',
  HealthAndSafety: 'HeartPulse',
  ChildCare: 'Baby',
  BeachAccess: 'Palmtree',
  LocalBar: 'Wine',
  FitnessCenter: 'Dumbbell',
  LocalTaxi: 'Car',
  Pool: 'Waves',
}

const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  ACTIVITY_ICON_OPTIONS.map((item) => [item.key, item.Icon]),
)

export function resolveActivityIconKey(name?: string) {
  if (!name) return ACTIVITY_ICON_OPTIONS[0].key
  if (ICON_MAP[name]) return name
  const mapped = LEGACY_ICON_KEYS[name]
  if (mapped && ICON_MAP[mapped]) return mapped
  return ACTIVITY_ICON_OPTIONS[0].key
}

export function getActivityIcon(name?: string): LucideIcon {
  return ICON_MAP[resolveActivityIconKey(name)] || Briefcase
}
